// ——— Trilha de auditoria: conversa por opções (Fases 4.1, 4.3–4.6) ———
// Caminhos, níveis, opções, ramificações, frase final, histórico e
// reutilização. Mesma coleção e mesmo writeAudit da pergunta fechada: o
// histórico de um paciente é UM só, e os dois modos aparecem lado a lado na
// ordem em que aconteceram.

export type OptionConversationEventType =
  // Caminho
  | "CONVERSATION_PATH_STARTED"
  | "CONVERSATION_PATH_PAUSED"
  | "CONVERSATION_PATH_RESUMED"
  | "CONVERSATION_PATH_COMPLETED"
  | "CONVERSATION_PATH_INTERRUPTED"
  | "CONVERSATION_PATH_RESTARTED"
  // Nível
  | "OPTION_LEVEL_CREATED"
  | "OPTION_LEVEL_REVIEWED"
  | "OPTION_LEVEL_PRESENTED"
  | "OPTION_LEVEL_REUSED"
  | "OPTION_LEVEL_EDIT_REQUESTED"
  | "OPTION_LEVEL_REPLACED"
  // Escolha
  | "OPTION_SELECTED"
  | "OPTION_CHANGED"
  | "OPTION_SELECTION_REMOVED"
  | "OPTION_CONFIRMED"
  // Navegação e ramificação
  | "PATH_LEVEL_RETURNED"
  | "PATH_BRANCH_DEACTIVATED"
  | "PATH_BRANCH_CREATED"
  | "PATH_CHANGED"
  // Frase final
  | "FINAL_STATEMENT_DRAFTED"
  | "FINAL_STATEMENT_EDITED"
  | "FINAL_STATEMENT_PRESENTED"
  | "FINAL_STATEMENT_CONFIRMED"
  | "FINAL_STATEMENT_REJECTED"
  | "FINAL_STATEMENT_REUSED"
  | "FINAL_STATEMENT_EDIT_REQUESTED"
  | "FINAL_STATEMENT_REPLACED"
  // Histórico
  | "HISTORY_ITEM_OPENED"
  | "CONTENT_REUSED";

export const OPTION_CONVERSATION_EVENT_TYPES: readonly OptionConversationEventType[] =
  [
    "CONVERSATION_PATH_STARTED",
    "CONVERSATION_PATH_PAUSED",
    "CONVERSATION_PATH_RESUMED",
    "CONVERSATION_PATH_COMPLETED",
    "CONVERSATION_PATH_INTERRUPTED",
    "CONVERSATION_PATH_RESTARTED",
    "OPTION_LEVEL_CREATED",
    "OPTION_LEVEL_REVIEWED",
    "OPTION_LEVEL_PRESENTED",
    "OPTION_LEVEL_REUSED",
    "OPTION_LEVEL_EDIT_REQUESTED",
    "OPTION_LEVEL_REPLACED",
    "OPTION_SELECTED",
    "OPTION_CHANGED",
    "OPTION_SELECTION_REMOVED",
    "OPTION_CONFIRMED",
    "PATH_LEVEL_RETURNED",
    "PATH_BRANCH_DEACTIVATED",
    "PATH_BRANCH_CREATED",
    "PATH_CHANGED",
    "FINAL_STATEMENT_DRAFTED",
    "FINAL_STATEMENT_EDITED",
    "FINAL_STATEMENT_PRESENTED",
    "FINAL_STATEMENT_CONFIRMED",
    "FINAL_STATEMENT_REJECTED",
    "FINAL_STATEMENT_REUSED",
    "FINAL_STATEMENT_EDIT_REQUESTED",
    "FINAL_STATEMENT_REPLACED",
    "HISTORY_ITEM_OPENED",
    "CONTENT_REUSED",
  ] as const;
